In [1]:
import numpy as np

In [2]:
# 1번 문제

## 균등분포식으로 size 각각 15, 6개 매트릭스를 만들고 reshape(-1,)으로 각각 적용
arr1 = np.random.uniform(0,1,15).reshape(-1,3)
arr2 = np.random.uniform(0,1,6).reshape(-1,2)

dot = arr1@arr2

## 행렬연산은 dot말고 @로도 표현 가능

print(dot,dot.shape)

[[0.36075075 0.60840331]
 [0.29223437 0.62459714]
 [0.36362706 0.39139762]
 [0.09360953 0.49162107]
 [0.13148239 0.53499772]] (5, 2)


In [3]:
# 2번 문제

arr1 = np.array([[5,7],[9,11]], float)
arr2 = np.array([[2,4],[6,8]], float)
# dtype을 지정하지 않으면 자동으로 int64로 적용됩니다.

concat_1 = print(np.concatenate((arr1,arr2),axis=0))
concat_2 = print(np.concatenate((arr1,arr2),axis=1))

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [4]:
# 3번 문제
xy= np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60]], float)
x_train=xy[0,:]
y_train=xy[1,:]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [5]:
#4번 문제

In [8]:
arr3=np.array([[1,1,1],[2,2,2]])
arr3.shape

(2, 3)